repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.3.2
    hooks:
      - id: cspell
        name: Spell check
        args: ["--no-progress", "--show-suggestions"]
        files: \.(md|mdx|js|jsx|ts|tsx)$

  - repo: local
    hooks:
      - id: markdown-link-check
        name: Check markdown links
        entry: markdown-link-check
        language: node
        files: \.(md|mdx)$
        args: ["--config", ".markdown-link-check.json"]
        additional_dependencies: ["markdown-link-check@3.12.1"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8.57.0
          - "@typescript-eslint/eslint-plugin@6.21.0"
          - "@typescript-eslint/parser@6.21.0"
          - "eslint-plugin-react@7.33.2"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
